kscripting/kscript

src/main/kotlin/kscript/app/Kscript.kt

A way to override //KOTLIN_OPTS lines in a script.
Supersedes #38.

Append $KSCRIPT_KOTLIN_OPTS to kotlin runtime opts.

---

README.md

The Intellij support is great, but I had to do some external googling after initially getting the error
```
/Users/eli_hart/.sdkman/candidates/kscript/current/bin/kscript: line 13: exec: idea: not found
```
I thought it would be nice to make this explicit.

Add instructions for idea command line launcher

---

kscript
src/main/kotlin/kscript/app/Kscript.kt

Fixes https://github.com/holgerbrandl/kscript/issues/98
Test:
- ensure `kscript "println(args.asList())" 0 1 "2 3" '4 5' '6"7' "7'8"` prints: `[0, 1, 2 3, 4 5, 6"7, 7'8]`
- same as above, but for `--package`d script

Fixed space-containing argument propagation

---

examples/classpath_example.kts

This suggest a different output from the example and replaces sample Usage text with one explaining kscript. The usage I put here is different from one in the application. This is how I understood your documentation. If it is incorrect then you may get an idea what in README is not clear.

Improve docopt example

---

src/main/kotlin/kscript/app/AppHelpers.kt
test/resources/diamond.kts

add a set of already added files and check if files was already added, in such case do not try to add it again
This happened to me while trying to include same files from multiple files (diamond topology)
got this exception when starting an idea project:
Exception in thread "main" kotlin.io.FileAlreadyExistsException: .../kscripts/utils.kt -> /Users/oshai/.kscript/kscript_tmp_project__ksuite.kts_1530089926297/src/utils.kt: The destination file already exists.
at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:193)
at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:184)
at kscript.app.AppHelpersKt.createSymLink(AppHelpers.kt:267)
at kscript.app.AppHelpersKt.launchIdeaWithKscriptlet(AppHelpers.kt:254)
at kscript.app.KscriptKt.main(Kscript.kt:140)
at …

allow to include same file from multiple files

---

README.md

Looks like the previous sdkman install page link was broken. Updating with a working one.

Updated link to sdkman install page

---

src/main/kotlin/kscript/app/AppHelpers.kt

There is no functional change. I think it would be easier if we don't need to change the hardcoded version strings each time we want to change kotlin version.

Replace hardcoded kotlin version to KotlinVersion.CURRENT

---

src/main/kotlin/kscript/app/DependencyUtil.kt
src/main/kotlin/kscript/app/Script.kt
src/test/kotlin/Tests.kt
test/resources/depends_on_dynamic.kts
test/test_suite.sh

for maven these are wrappend in a range
`1.2.3+` -> `[1.2.3,)`
for gradle they are not touched and just passed as is
closes #166

support dynamic versions ending with `+` 

---

src/main/kotlin/kscript/app/AppHelpers.kt
src/main/kotlin/kscript/app/Kscript.kt

Currently kscript is not working on Windows in cygwin.
> /cygdrive/c/kotlin/scripting
$ kscript 'println("hello world")'
error: please specify at least one name or file to run
Most of the issues were caused by not quoting paths containing windows path separator '\' that was actually escaping characters in cygwin.
The '--package' didn't work for similar reason. In the generated gradle build file the actual script was added with windows path separators '\'. Now using invariant separator '/'.

cygwin support improvements

---

src/main/kotlin/kscript/app/ResolveIncludes.kt

Hi,
This change enables to include files relative to home directory like below:
@file:Include("~/my-kscript/utils.kt")

Support "~" in INCLUDE

---

.travis.yml

This makes it so tests can pass on forks too if contributors enable them in Travis.

Don't hardcode the KSCRIPT_HOME path in Travis

---

src/main/kotlin/kscript/app/DependencyUtil.kt

This is a simple bug fix PR. After aether change, kscript does dependency resolution repeatedly on Windows.

Fix cache check bug on Windows

---

src/main/kotlin/kscript/app/Kscript.kt
test/resources/includes/shebang_mode_includes
test/test_suite.sh

The documentation is a bit unclear on what the INCLUDE directive paths are supposed to be relative to - the workdir or script dir? This change makes them relative to the script dir, so that scripts can be invoked from any workdir.
**Old behavior:**
Main script file: "my-script":
```
#!/usr/bin/env kscript
//INCLUDE src/helpers.kt
doIt();
```
Support file: "src/helpers.kt":
```
fun doIt() {
println("Do something")
}
```
This works: `$ ./my-script`
This fails: `$ cd src/; ../my-script`
[kscript] [ERROR] Failed to resolve //INCLUDE 'src/helpers.kt'
**New behavior:**
This works: `$ ./my-script`
This works: `$ cd src/; ../my-script`

Make INCLUDE directive files relative to script dir

---

misc/boostrap_header.sh

Fixes #227 resolving following issues:
- Misprint in quotes mark lads to fail after installing sdkman — command resolves to `$SDKMAN_DIR/bin/sdkman-init.sh` instead of `/home/olegg/.sdkman/bin/sdkman-init.sh`
- Missing java installation routine — when running `kscript` on a fresh Ubuntu installation, script crashes with error message `/home/olegg/.sdkman/candidates/kotlin/current/bin/kotlinc: line 80: java: command not found`
- Failure on script re-run — if `sdkman` already had `kscript` installed, it was erring out instead of silently continue.
- Failure on initial install — after all required tools are installed, we should re-source sdkman, so shell will see all newly installed tools.

Fix bootstrap header

---

src/main/kotlin/kscript/app/AppHelpers.kt
src/main/kotlin/kscript/app/Kscript.kt
test/test_suite.sh

Create a default Run Configuration for Intellij when using the `idea`
option. Achieved by creating a `Main` configuration within
`.idea/runConfigurations`. The `userArgs` are also passed along by
default.
Running `kscript --idea test.kts a b c` will now create a default run configuration as seen in the screenshots below.
See this issue for more info: https://github.com/holgerbrandl/kscript/issues/243

Create a default Run Configuration for Idea

---

docs/user_guide.md
src/main/kotlin/kscript/app/AppHelpers.kt

Implements discussion from https://github.com/holgerbrandl/kscript/issues/245
Let me know if you have a preference on what the `--idea` output is for describing the project directory.
Also, if you support a `kscript --test MyScript.kts` command I can add that too

Add basic testing support

---

README.md
src/main/kotlin/kscript/app/DependencyUtil.kt

I have to use the private nexus repository in gitlab-ci.
We use only authenticated access to it. But I mustn't write a password in scripts.
PS: I've chosen '@' as a symbol ('$' isn't possible in Kotlin). Maybe You will choose another one.
PPS: I have not found any other point to use environment variables.

Add "Authentication from environment"

---

misc/kscript_release.sh

As [mentioned on AUR][1], the latest release there is broken. This was due to the PKGBUILD generation not retaining the variables, but rather attempting to resolve them at release script execution time. Here's a before/after of what's generated:
**Before:**
```
pkgname=kscript
pkgver=2.9.0
pkgrel=1
pkgdesc='Enhanced scripting support for Kotlin on *nix-based systems'
arch=('any')
url='https://github.com/holgerbrandl/kscript'
license=('MIT')
depends=('kotlin')
source=("-.bin.zip::https://github.com/holgerbrandl//releases/download/v/--bin.zip")
sha256sums=('3d62b0db226566506a2531d765547595867230cd5d44dbedc65301cadfecdaaf')
package() {
cd "/-/bin"
install -Dm 755 kscript "/usr/bin/kscript"
install -Dm 644 kscript.jar "/usr/bin/kscript.jar"
}
```
**After:**
```
pkgname=kscript
pkgver=2.9.0 …
```

Fix PKGBUIILD creation for AUR release

---

build.gradle.kts

Hi
This pull request fixes the incremental task `test`.
This task depends on some test resources included in the `test/resources` directory.
However, this directory is not declared as input to this task, so tests are not executed whenever there are updates to any of those dependent files.
This commit fixes this issue by declaring `test/resources` as input of task `test`.

Add missing inputs to the incremental task "test"

---

src/main/kotlin/kscript/app/DependencyUtil.kt

Bintray does not support `http` anymore

Use https version of Bintray for dependency resolution

---

README.md
src/main/kotlin/kscript/app/AppHelpers.kt

Depending on how your intellij was installed it has not the same command set to launch, so this PR allows to tell kscript what command needs to be considered
Allow the possibility to customize kscript to set your intellij launch command

Add option to launch temp intellij as custom command through env property

---

build.gradle.kts

No specific reason other than not having to download too many kotlin versions.

bump kotlin version to 1.3.72

---

src/main/kotlin/kscript/app/AppHelpers.kt

Create symlinks for included files in the same relative path to the main script that they are in the actual script location.
e.g. right now if you have 
**`Main.kt`**:
```kotlin
#!/usr/bin/env kscript
@file:Include("./directory/Include.kt")
fun main(args: Array<String>) {
println(helloWorld)
}
}
```
**`directory/Include.kt`**:
```kotlin
#!/usr/bin/env kscript
val helloWorld = "Hello World!"
```
in the idea project they will end up like this:
```
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── local.properties
└── src
├── Include.kt -> /Users/arossbacher/Documents/directory/Include.kt
└── Main.kt -> /Users/arossbacher/Documents/Main.kt
```
The idea project itself will not be able to run the …

Fix idea project symlinks for complex projects

---

misc/boostrap_header.sh

Error messages in: #270
In `misc/boostrap_header.sh`, it installs SDKMAN using
```bash
curl "https://get.sdkman.io" | bash 1>&2 && \
echo_and_eval source "$SDKMAN_DIR/bin/sdkman-init.sh"
```
After that, it installs Java, Kotlin, Grade, and Kscript. 
It uses `$SDKMAN_DIR`, but it can't be retrieved from the previous sdkman installation script. so it causes the issue: `misc/boostrap_header.sh` runs `/bin/sdkman-init.sh` since `$SDKMAN_DIR` is not set. In the meantime, the rest of the installation will be failed.
I added the declaration of the `SDKMAN_DIR` before SDKMAN installation script runs. The value is same as the one SDKMAN script uses.
There are 2 reasons I declare it explicitly:
* The SDKMAN installation script will use it as the SDKMAN's location. So whatever the default location …

Fix bootstrap script env variable issue

---

src/main/kotlin/kscript/app/AppHelpers.kt

When you run with the `--idea` option `kscript` is creating an IDEA run configuration for your script.
If you have a `.kts` script it makes sense to create a `bash` type run configuration. But those do not work if your script is a `.kt` script with a `main` method.
This change will create a Kotlin run configuration in that case.
This will also add a gradle wrapper to the tmp project used for editing the script in IDEA.

Add Kotlin run configuration for .kt based scripts plus add gradle wrapper.

---

src/main/kotlin/kscript/app/AppHelpers.kt

This can otherwise lead to issues if one path is relative and the other is not.

Use absolute paths to avoid issues with relative paths and relativize

---

src/main/kotlin/kscript/app/Kscript.kt

When `kotlin -java` contains Java version output like so:
```
Kotlin version 1.4.20-release-308 (JRE 15.0.1+9)
```
then `kscript --version` shows
```
Java      : JRE 15.0.1+9)
```
Note the last character, a closing parenthesis that shouldn't be there.
This commit fixes that issue.

Fix Java info in `kscript --version`

---

docs/user_guide.md

Document how to use a GitHub Action for running unit tests in pull requests against your main branch 
The [helper script](https://gist.github.com/elihart/019bd116d3fa0d6214b7396eedc4b206) by [@elihart](https://gist.github.com/elihart) was really helpful for running unit tests locally. But I was wanting to create an even easier way to run this on CI using GitHub Actions so I created a new action called [kscript-action](https://github.com/plusmobileapps/kscript-action) which runs that helper script in a docker container. I was able to use this in a [sample project](https://github.com/plusmobileapps/kotlin-scripting) and validated that it worked. 
There was some flakiness in the script sometimes timing out so maybe in a future iteration can allow the user to pass a timeout argument in the …

update user guide testing on ci to include a github action section

---

build.gradle.kts

This allows easily running using `java -jar ktscript.jar` , especially useful on Windows without needing to rely on the bash script `ktscript`.

build.gradle.kts: Executable JAR

---

NEWS.md
src/main/kotlin/kscript/app/model/OsType.kt

Changed equals to contains so run for os 'darwin21' also works

Fix for OsType comparison logic

---

src/kscript.bat

The scenario:
1. Unpack kscript files to a folder which is not in the PATH
2. Make a symlink to kscript.bat
3. Run `kscript "println('1')"` in cmd or `kscript """println('1')"""` in PowerShell.
You will get the following error:
```
Error: Could not find or load main class io.github.kscripting.kscript.KscriptKt
Caused by: java.lang.ClassNotFoundException: io.github.kscripting.kscript.KscriptKt
```
The reason is that kscript.bat strictly depends on kscript.bat being in your PATH. It uses `where` (`where.exe` from `System32`)  to locate the kscript.bat in the PATH. 
Another problem with this approach is that when executed in PowerShell,  `where` becomes an alias to the `Where-Object` PowerShell function, which returns an empty string.
The provided solution both makes symlinks work and fixes …

Fix calling kscript.bat by symlink and PowerShell compatibility

---

README.adoc

Provides windows installation guide for https://github.com/kscripting/kscript/issues/391

Add scoop installation doc

---

build.gradle.kts
src/main/kotlin/io/github/kscripting/kscript/resolver/CommandResolver.kt
src/test/kotlin/io/github/kscripting/kscript/resolver/CommandResolverTest.kt

As explained in #397 and here https://stackoverflow.com/a/356014/1907778 `cmd /c` has problems with spaces in paths, which normally can be corrected in cmd / bat using double quotes. But if using some argument with `cmd /c <argument>`, the behavior is special for backwards compatibility if the first character is a double quote, in which case it will remove this first character as well as the last double quote in the argument, completely breaking the existing quotations.
Alternatives I have not taken:
* You could use path segment wise quotation like `C:\"my folder"\"my subfolder"\kotlinc.bat`. This seemed to be a too invasive use.
* Instead of using absolute paths, just set the ProcessBuilder's `directory` to kotlinc's parent dir, and call it with a relative path. Cleanest solution, but …

quote kotlinc path on windows (fixes #397)
